### ISSUE TITLE
border-right on monokai is unusually bright and distracting

### ISSUE THREAD

**Issue by acowlikeobject** [dunovank/jupyter-themes#119]
The border-right properties on monokai is set to `#a6e22e`.  Having this neon green line running vertically through the entire notebook is quite distracting.  Other themes have more subtle borders.

Changing it to `#49483e` (which is used throughout monokai), for example, produces a much less distracting (but still visible) border.

Before:
![before](https://cloud.githubusercontent.com/assets/3529638/25521004/a7a57eda-2c30-11e7-8f8a-79548705049d.png)

After:
![after](https://cloud.githubusercontent.com/assets/3529638/25521007/aa5bd660-2c30-11e7-9377-fe6dad2eaab7.png)

**Comment by dunovank** [comment]
Fully agree. The monokai theme was submitted as a PR and I've been meaning to spend some time smoothing out some of the stylistic edges but haven't gotten around to it. I've changeed the prompt border color as suggested so that will be included in the next release. By all means, if you want to submit a PR with style improvements to monokai, please do.

**Comment by dunovank** [comment]
@acowlikeobject have you had a chance to check the new version?

**Comment by acowlikeobject** [comment]
@dunovank Yes, looks good!  And apologies, but I barely know what CSS is, so not sure I should be mucking about with it too much :).

Anyway, will close this out.
