### ISSUE TITLE
Notebook toolbar not showing

### ISSUE THREAD

**Issue by pgensler** [dunovank/jupyter-themes#157]
Hi,

When I try to view the notebook toolbar with the menu at the top, it seems like the jupyter notebook wont let me view it, and I'm wondering if it has something to do with the theme I may be using. Thoughts on this? My jupyter notebook is running fine with the grade3 theme, but View-> Toggle  Header and Toggle Toolbar are not working. I am running Python 3 with the latest version of jupyter themes I think. Let me know if you need more information.

**Comment by dunovank** [comment]
Use the `-T` flag to toggle the toolbar on when installing a theme. 
e.g.:
`jt -t grade3 -T`

**Comment by pgensler** [comment]
So is there any particular reason why that is not set as a default on the theme, or in general? Wouldn't you want the toolbar to be automatically enabled, and use the flag to disable it if you diden't need it?

**Comment by dunovank** [comment]
I've turned the toolbar off by default since all of the buttons have hot keys associated with them. More efficient and more space at the top of the screen to view code. I see your point as some users will not be familiar with the hotkeys but it's been the default for so long that I'm hesitant to switch it. Will consider reversing the default behavior in the future but going to sit on it for now.

**Comment by pgensler** [comment]
Yeah it just seems odd that in order to "enable" a theme, I would essentially have to re-enable all the features of the notebook, as I'm assuming it would all be controlled as flags for configuration?

**Comment by dunovank** [comment]
I would just have the default behavior be to have the toolbar enabled and the `-T` flag would toggle it off. And it's not like installing a theme requires you to ren-enable every feature of the notebook. It's one feature and one that many people prefer to have toggled off since hotkeys make it unnecessary.

**Comment by pgensler** [comment]
In it's current state today......yes it would require you to re-enable the features you wish to use. Hotkeys are definitely nice to have, but simple features made accessible to new users has its appeal. Thanks for considering.

**Comment by dunovank** [comment]
In its current state today..... no. You use a single flag when installing the theme to toggle the toolbar as visible. That is one feature. Not every feature. It's just one. Look I'll even count it out. 1. Toolbar. [End of list]. Also, this is described in the readme.
