### ISSUE TITLE
Cannot fit the end of text in a cell

### ISSUE THREAD

**Issue by sabotage3d** [dunovank/jupyter-themes#204]
Hi,
I am having a small issue. I cannot fit the end of text in a cell. Is there any settings that can help?
![notebook_cell](https://user-images.githubusercontent.com/4654347/32806907-083b8b2a-c986-11e7-88b3-7e470f77d7d8.png)

**Comment by arthurire** [comment]
Same issue...
![image](https://user-images.githubusercontent.com/27836456/43812341-70a6b330-9af3-11e8-824b-952049ac920c.png)

**Comment by icecat2012** [comment]
I think this bug might be different width of the `input_area` and `cm-s-ipython.CodeMirror`
The following steps work for me. I am not sure if it works to everyone because I already edited some css code before.
If this is correct solution, hope someone can make a pull requests. Thanks
1.
find 
`div.input_area {
 background-color: #293340;
 background: #293340;
 padding-right: 1.2em;   <-------find this value
 border: 0px;
 border-radius: 0px;
 border-top-right-radius: 4px;
 border-bottom-right-radius: 4px;
}`

2.
`.cm-s-ipython.CodeMirror {
 font-family: monospace, monospace;
 font-size: 11pt;
 background: #293340;
 color: #cdd2e9;
 padding-right: 1.2em;    <---------add this line (copy it to here)
 border-radius: 2px;
 font-style: normal;
 font-weight: normal;
}`
