### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by yc-z** [dunovank/jupyter-themes#21]
I use the below code and have installed  the Source-Code-Pro font, but it doesn't work.
`jupyter-theme -T -t oceans16 -f Source-Code-Pro -fs 16`

**Comment by dunovank** [comment]
Do you get an error? Or just not the expected changes when you start your jupyter notebook?

**Comment by yc-z** [comment]
There is no error. My python version is 3.5.1, OS win 10.
![qq](https://cloud.githubusercontent.com/assets/15177069/14063234/c3cb8970-f3fa-11e5-8d89-6cf2558b2c8a.png)

**Comment by dunovank** [comment]
This doesn't seem to be an issue with the font-size flag but it's tough for me to rule out since don't have access to a windows machine and currently don't have python 3.* installed. So it's possible that there's a larger (cross-platform or version-related) issue. Were you ever able to get this sorted out? 

You might try manually setting the monospace font in your browser. Obviously, that doesn't resolve this issue if there's a problem with the code but just thought I'd mention it a temporary work-around.

**Comment by yc-z** [comment]
I change the font-size in the below code and now it works. 
```
div.CodeMirror pre {font-family:'YaHei Consolas Hybrid', monospace; font-size: 14pt;}

/* Set CodeCell font-size*/
div.CodeMirror pre {font-size: 14pt !important;}
```

Maybe it is a python version related issue. There is no problem when I  use python 2.* to test. But for python 3.*, the default font and font-size can't be changed.

**Comment by dunovank** [comment]
should now be able to set the font-size using the cl argument -fs (as described in README) when setting the theme.
