### ISSUE TITLE
install error: Cannot uninstall 'jedi'

### ISSUE THREAD

**Issue by jeffsaremi** [dunovank/jupyter-themes#258]
tried the following commands:

`pip install jupyterthemes`

and

`pip install --upgrade jupyterthemes`

they both end up in the following:

Installing collected packages: jedi, ipython, jupyterthemes
  Found existing installation: jedi 0.9.0
Cannot uninstall 'jedi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by dunovank** [comment]
Hmm.. I've never seen this before and jedi is not a requirement or dependency for installing jupyterthemes. However, I just ran `pip install --upgrade jupyterthemes` and saw that jedi was installed, which makes me think that it is a newer dependency of one of JT's dependencies (e.g., matplotlib etc.). 

What happens when you run this:
`pip install --upgrade jupyterthemes --no-deps`

**Comment by jeffsaremi** [comment]
that worked! thanks a lot

> Installing collected packages: jupyterthemes
> Successfully installed jupyterthemes-0.19.1
