### ISSUE TITLE
Toolbar covers ToC

### ISSUE THREAD

**Issue by pccampbell** [dunovank/jupyter-themes#349]
I would love to use themes, but unfortunately it results in the toolbar covering the Table of Contents extension. Don't know if there's an easy fix. You can move the ToC to the right, but that's not ideal for me. 
![theme_fail](https://user-images.githubusercontent.com/7552710/60290957-78017080-98df-11e9-9550-114b4110580b.PNG)

**Comment by jayzed82** [comment]
Same problem here after updating to last jupyter notebook version (5.7.8).

**Comment by chris-tran-16** [comment]
Not sure what the issue is at the moment, but for now I've just removed this part from my ~/.jupyter/custom/custom.css

You may have similar lines (mine started on line 35)

> div#maintoolbar {
 position: absolute;
 width: 90%;
 margin-left: -10%;
 padding-right: 8%;
 float: left;
 background: transparent !important;
}
#maintoolbar {
 margin-bottom: -3px;
 margin-top: 0px;
 border: 0px;
 min-height: 27px;
 padding-top: 2px;
 padding-bottom: 0px;
}
#maintoolbar .container {
 width: 75%;
 margin-right: auto;
 margin-left: auto;
}

**Comment by HsuHeinrich** [comment]
Awesome!

**Comment by logancyang** [comment]
I made the css change and it didn't work for me
![Screenshot 2020-05-09 16 06 30](https://user-images.githubusercontent.com/4860545/81483839-12745500-920f-11ea-8e2a-b226eb3d6117.png)

**Comment by thakkarparth007** [comment]
Pasting this in my custom.css works for me.

```
#toc-wrapper {
  top: 80px !important;
}
div#maintoolbar {
  margin-left: -20px !important;
  background: white !important;
  width: 100% !important;
  padding-left: 25px !important;
}
```

![image](https://user-images.githubusercontent.com/747423/107354374-157cd880-6af4-11eb-8ee7-48ac4fc10332.png)
