### ISSUE TITLE
Markdown cell with same background color of code cell in grade3 theme

### ISSUE THREAD

**Issue by fbrundu** [dunovank/jupyter-themes#63]
Hi,
I don't know if this is a regression or a feature (if I remember correctly previous version was different).
The markdown cells in theme grade3 now display the same background color of code cells (gray instead of white):

<img width="957" alt="screen shot 2016-10-08 at 23 58 13" src="https://cloud.githubusercontent.com/assets/697622/19216214/722348da-8db3-11e6-9c86-662027cfabd7.png">

Is it a regression or a feature?

Francesco

**Comment by dunovank** [comment]
Ah, thanks for this. I changed it back so that grade3 defaults to the "altlayout" (-alt) which just makes the text/md cell background the same as the notebook background. All dark themes will still default to having txt/md cells with the same background color as code-cells. Would you mind double checking that this is fixed in the latest version (v0.13.6)?

**Comment by fbrundu** [comment]
Seems ok now. Thanks
