### ISSUE TITLE
Themes seem to remove the "Upload" button 

### ISSUE THREAD

**Issue by dzackgarza** [dunovank/jupyter-themes#67]
Here's the one I'm referring to, on Jupyter's main file tree page. After applying a theme, the "Upload" button disappears (although the "New" and refresh buttons remain)

![image](https://cloud.githubusercontent.com/assets/1149853/19421565/14785b56-93b9-11e6-94c8-b96743f668b7.png)

**Comment by BrandonNowlin** [comment]
I am sure you may have already figured this out, but a work around for this issue is to remove the following lines out of the generated CSS:

`.alternate_upload .btn-upload,

.alternate_upload .btn-upload {
 display: none;
}
.alternate_upload input.fileinput {
 display: none;
}
`

It might be slightly different depending on what options you choose, but I imagine if you search for upload in the code and remove the parts that do something similar to this you should be good.

**Comment by smblance** [comment]
The causing block in in the */layout/notebook.less*:
`.alternate_upload .btn-upload {
    display: none;
}`
What's the point in disabling the upload button?

**Comment by dunovank** [comment]
Ahh thanks, I think I had commented this line out when running some tests, forgot to uncomment. I'll correct this asap.

**Comment by dunovank** [comment]
Should be fixed in the latest version
