### ISSUE TITLE
Error message as [Errno 13] Permission denied: '/tmp/yacctab.py'

### ISSUE THREAD

**Issue by michaelchen33** [dunovank/jupyter-themes#76]
I am under virtualenv and try $  jt -t onedork -T -N but it seems like something went wrong?

**Comment by ssoftcheck** [comment]
just in case anyone else sees this...

I deleted yacctab.py and the custom.css was successfully created

**Comment by mjskier** [comment]
This is a common problem in a multiuser environment: `jt -t sometheme` leaves a /tmp/yacctab.py behind, owned by the user who invoked the command.

If another user then tries to run <jt -t> the call to `lesscpy.compile(tempfile)` in stylefx.py will fail until the original owner (or an admin) removes the file.

So the problem is really in the lesscpy package for leaving temp files around.
But as a workaround until it is fixed, an `os.remove("/tmp/yacctab.py")` after the call to lesscpy.compile would do the job.
